### ISSUE TITLE
new list - my blacklist

### ISSUE THREAD

**Issue by ghost** [Laicure/HostsY_hosts#9]
Hi,

if the list meets your requirements please check my personal blacklist and add if necessary. I make sure that this list does not contain any false positive domains. It will be extended and updated regularly. The list blocks ads, tracking, telemetry, metrics and more.

Blocklist formats:

Domains - https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/personal.txt

Hosts - https://raw.githubusercontent.com/Zelo72/hosts/main/personal.txt

AdBlock/AdGuard - https://raw.githubusercontent.com/Zelo72/adguard/main/personal.adblock

Thanks and greets,
Gerd

**Comment by Laicure** [comment]
Thanks for the suggestion.

I did a very quick check on the main sources:
1. Source: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/data/black.list
2. Source: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/data/black.list.block

It has a lot of random automated-domains from APIs, CDNs, Assets and JS that will highly break other user's browsing experience.

Do you have a more personally curated "lite" list?

**Comment by ghost** [comment]
Thanks, but I don't see any APIs CDNs ... on my list that block any functionality or limit any user experience. Do you have an example?

I will check my list again ...

**Comment by Laicure** [comment]
I don't know what happened here:
![image](https://user-images.githubusercontent.com/8619566/135059729-7849aa15-11fa-4393-9e92-6fe8e9e075a5.png)

I think, you did a lot of clean-up on this: https://github.com/Zelo72/rpi/commits/96949e9662b7a758d3eaadd8104635fd8dd68d9e/pihole/blocklists/data/black.list
this one has too much.

I added a source here last time that contains 300k+ domains, from hosts-file.net.
It's good but strains the devices too much.

Anyway, we don't want some automated list of domains. Hand-picked domains is a lot more better. Check [StevenBlack's](https://github.com/StevenBlack/hosts) hosts repo, he only picks sources that are well-curated and have personalized commits.
